# noinspection YAMLSchemaValidation
version: 1

labels:
  # Type labels
  - label: "@type/build"
    title: '^build(?:\(.+\))?\!?:'
    files:
      - "**/pubspec.yaml$"
      - "**/melos.yaml$"

  - label: "@type/ci"
    title: '^ci(?:\(.+\))?\!?:'
    files:
      - '\.github/.+'
      - "scripts/.+"
      - "tools/.+"

  - label: "@type/docs"
    title: '^docs:(?:\(.+\))?\!?:'
    files:
      - "docs/.+"
      - "**/README.md$"

  - label: "@type/feature"
    title: '^feat:(?:\(.+\))?\!?:'

  - label: "@type/fix"
    title: '^fix:(?:\(.+\))?\!?:'

  - label: "@type/improve"
    title: '^(style|refactor|perf)(?:\(.+\))?\!?:'

  # App Package labels
  - label: "@application"
    files:
      - "app/.+"

  - label: "@backend"
    files:
      - "backend/.+"

  - label: "@catalog"
    files:
      - "catalog/.+"

  # Core Package labels
  - label: "@core/analytics"
    files:
      - "core/analytics/.+"

  - label: "@core/common"
    files:
      - "core/common/.+"

  - label: "@core/data"
    files:
      - "core/data/.+"

  - label: "@core/database"
    files:
      - "core/database/.+"

  - label: "@core/datastore"
    files:
      - "core/datastore/.+"

  - label: "@core/designsystem"
    files:
      - "core/designsystem/.+"

  - label: "@core/domain"
    files:
      - "core/domain/.+"

  - label: "@core/model"
    files:
      - "core/model/.+"

  - label: "@core/network"
    files:
      - "core/network/.+"

  - label: "@core/testing"
    files:
      - "core/testing/.+"

  - label: "@core/ui"
    files:
      - "core/ui/.+"

  # Feature Package labels
  - label: "@feature/auth"
    files:
      - "feature/auth/.+"

  - label: "@feature/home"
    files:
      - "feature/home/.+"

  - label: "@feature/quest"
    files:
      - "feature/quest/.+"

  - label: "@feature/settings"
    files:
      - "feature/settings/.+"
