name: backend
description: An new Dart Frog application
version: 0.1.0
publish_to: none

environment:
  sdk: 3.2.6

dependencies:
  dart_frog: 1.1.0

dev_dependencies:
  mocktail: 1.0.3
  test: 1.25.2
  yumemi_lints: 1.6.0
