name: backend
description: An new Dart Frog application
version: 0.1.0
publish_to: none

environment:
  sdk: 3.4.3

dependencies:
  dart_frog: 1.1.0

dev_dependencies:
  mocktail: 1.0.4
  test: 1.25.7
  yumemi_lints: 1.7.0
