name: catalog
description: "Boilerplate Catalog"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: 3.4.3

dependencies:
  core_designsystem:
    # noinspection DartPathPackageReference
    path: ../core/designsystem
  cupertino_icons: 1.0.8
  dynamic_color: 1.7.0
  flutter:
    sdk: flutter
  widgetbook: 3.7.1
  widgetbook_annotation: 3.1.0

dev_dependencies:
  build_runner: 2.4.11
  widgetbook_generator: 3.7.0
  yumemi_lints: 1.7.0

flutter:
  uses-material-design: true
