name: core_database
description: This package provides local database operations.
version: 1.0.0
publish_to: "none"

environment:
  sdk: 3.2.6

dependencies:
  core_common:
    path: ../common
  core_model:
    path: ../model
  isar: 4.0.0-dev.14
  riverpod_annotation: 2.3.3

dev_dependencies:
  build_runner: 2.4.8
  core_testing:
    path: ../testing
  riverpod_generator: 2.3.9
  test: 1.25.2
  yumemi_lints: 1.5.0
