name: core_testing
description: This package provides convenience functions for testing, etc.
version: 1.0.0
publish_to: "none"

environment:
  sdk: 3.2.6

dependencies:
  core_common:
    path: ../common

dev_dependencies:
  test: 1.25.2
  yumemi_lints: 1.6.0
