name: core_testing
description: This package provides convenience functions for testing, etc.
version: 1.0.0
publish_to: "none"

environment:
  sdk: 3.4.4

dependencies:
  core_common:
    path: ../common

dev_dependencies:
  test: 1.25.8
  yumemi_lints: 1.7.0
