name: core_datastore
description: This package provides local preferences operations.
version: 1.0.0
publish_to: "none"

environment:
  sdk: 3.4.3

dependencies:
  core_common:
    path: ../common
  core_model:
    path: ../model

dev_dependencies:
  core_testing:
    path: ../testing
  test: 1.25.8
  yumemi_lints: 2.1.0
