name: "Deploy to GitHub Pages"

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      preview:
        required: true
        type: boolean
    secrets:
      gh-token:
        required: true

jobs:
  build:
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      contents: read
    runs-on: ubuntu-22.04
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      # https://github.com/marketplace/actions/mise-action
      - name: mise action
        uses: jdx/mise-action@d6e32c1796099e0f1f3ac741c220a8b7eae9e5dd # v2.0.6

      # https://github.com/marketplace/actions/melos-action
      - name: Melos action
        uses: bluefireteam/melos-action@6085791af7036f6366c9a4b9d55105c0ef9c6388 # v3

      # https://github.com/marketplace/actions/configure-github-pages
      - name: Configure GitHub Pages
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5.0.0

      - name: Build
        run: flutter build web --web-renderer html --release
        working-directory: ./catalog

      # https://github.com/marketplace/actions/upload-github-pages-artifact
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
        with:
          name: ${{ inputs.environment }}
          path: './catalog/build/web'

  # Deployment job
  deploy:
    environment:
      name: '${{ inputs.environment }}'
      url: ${{ steps.deployment.outputs.page_url }}
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    runs-on: ubuntu-22.04
    needs: build
    steps:
      # https://github.com/marketplace/actions/deploy-github-pages-site
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
        with:
          token: ${{ secrets.gh-token }}
          artifact_name: ${{ inputs.environment }}
          preview: ${{ inputs.preview }}
